import 'package:flutter/material.dart';

import 'northstar_color_tokens.dart';

/// **Canonical light / dark / white-label palettes in Dart** — edit here when
/// the design system evolves. This is the single source of truth for default
/// colors in this package (no runtime JSON loading).
///
/// Keep values aligned with the Figma variables export (DTCG JSON):
/// `Light.tokens.json`, `Dark.tokens.json`, `White Labeled.tokens.json`.
/// Material bridge fields ([surface], [outline], …) use the same hex as the
/// matching Figma keys (e.g. surface = Background Bright).
///
/// Pair with [NorthstarTheme.buildThemeData] and [NorthstarTypography] for
/// Material 3 text styles derived from the same [ColorScheme].
abstract final class NorthstarBaseTokens {
  const NorthstarBaseTokens._();

  /// Default light semantic colors (product “Northstar” baseline).

  static const NorthstarColorTokens light = NorthstarColorTokens(
    primary: Color(0xFF046AF2),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFEDF9FF),
    onPrimaryContainer: Color(0xFF104A98),
    secondary: Color(0xFF62D2F4),
    onSecondary: Color(0xFF202939),
    surface: Color(0xFFF8FAFC),
    onSurface: Color(0xFF202939),
    onSurfaceVariant: Color(0xFF697586),
    surfaceContainerLow: Color(0xFFF3F6F9),
    surfaceContainerHigh: Color(0xFFE3E8EF),
    outline: Color(0xFFCDD5DF),
    outlineVariant: Color(0xFFE3E8EF),
    error: Color(0xFFE91553),
    onError: Color(0xFFFFFFFF),
    success: Color(0xFF51961A),
    onSuccess: Color(0xFFFFFFFF),
    warning: Color(0xFFFBBF24),
    onWarning: Color(0xFF202939),
    inverseSurface: Color(0xFF00263F),
    onInverseSurface: Color(0xFFFFFFFF),
    background: Color(0xFFF3F6F9),
    backgroundBright: Color(0xFFF8FAFC),
    backgroundDim: Color(0xFFE3E8EF),
    border: Color(0xFFCDD5DF),
    card0: Color(0xFFFFFFFF),
    card10: Color(0xFFF8FAFC),
    card20: Color(0xFFF3F6F9),
    card30: Color(0xFFE3E8EF),
    card40: Color(0xFFCDD5DF),
    contentBlack: Color(0xFF202939),
    contentGray: Color(0xFF697586),
    contentGrayBright: Color(0xFF9AA4B2),
    contentWhite: Color(0xFFFFFFFF),
    divider: Color(0xFFE3E8EF),
    errorContainer: Color(0xFFFFE3E7),
    errorVariant: Color(0xFFFF6C8B),
    errorHover: Color(0xFFC50B46),
    logotype: Color(0xFF00263F),
    miscellaneousBlue: Color(0xFF046AF2),
    miscellaneousBlueContainer: Color(0xFFEDF9FF),
    miscellaneousBlueHover: Color(0xFF0B54C2),
    miscellaneousBlueVariant: Color(0xFF22A1FF),
    miscellaneousEmerald: Color(0xFF10B981),
    miscellaneousEmeraldContainer: Color(0xFFD1FAE5),
    miscellaneousEmeraldHover: Color(0xFF10B981),
    miscellaneousEmeraldVariant: Color(0xFF6EE7B7),
    miscellaneousIndigo: Color(0xFF6366F1),
    miscellaneousIndigoContainer: Color(0xFFC7D2FE),
    miscellaneousIndigoHover: Color(0xFF4F46E5),
    miscellaneousIndigoVariant: Color(0xFF818CF8),
    miscellaneousOnBlueContainer: Color(0xFF104A98),
    miscellaneousOnEmeraldContainer: Color(0xFF065F46),
    miscellaneousOnIndigoContainer: Color(0xFF312E81),
    miscellaneousOnOrangeContainer: Color(0xFF9A3412),
    miscellaneousOnPinkContainer: Color(0xFF9D174D),
    miscellaneousOnVioletContainer: Color(0xFF4C1D95),
    miscellaneousOrange: Color(0xFFF97316),
    miscellaneousOrangeContainer: Color(0xFFFFEDD5),
    miscellaneousOrangeHover: Color(0xFFEA580C),
    miscellaneousOrangeVariant: Color(0xFFFDBA74),
    miscellaneousPink: Color(0xFFEC4899),
    miscellaneousPinkContainer: Color(0xFFFBCFE8),
    miscellaneousPinkHover: Color(0xFFDB2777),
    miscellaneousPinkVariant: Color(0xFFF9A8D4),
    miscellaneousViolet: Color(0xFF7C3AED),
    miscellaneousVioletContainer: Color(0xFFEDE9FE),
    miscellaneousVioletHover: Color(0xFF6D28D9),
    miscellaneousVioletVariant: Color(0xFFC4B5FD),
    onErrorContainer: Color(0xFFA50C42),
    onSecondaryContainer: Color(0xFF0B91BE),
    onSuccessContainer: Color(0xFF345B19),
    onWarningContainer: Color(0xFF92400E),
    primaryHover: Color(0xFF0B54C2),
    primaryVariant: Color(0xFF22A1FF),
    secondaryContainer: Color(0xFFE1F5FD),
    secondaryHover: Color(0xFF41CAEF),
    secondaryVariant: Color(0xFFBDEAFA),
    successContainer: Color(0xFFE5F8CF),
    successHover: Color(0xFF3F7318),
    successVariant: Color(0xFF89D744),
    warningContainer: Color(0xFFFEF3C7),
    warningHover: Color(0xFFF59E0B),
    warningVariant: Color(0xFFFDE68A),
  );

  /// Default dark semantic colors.
  static const NorthstarColorTokens dark = NorthstarColorTokens(
    primary: Color(0xFF22A1FF),
    onPrimary: Color(0xFF121926),
    primaryContainer: Color(0xFF104A98),
    onPrimaryContainer: Color(0xFFD6F0FF),
    secondary: Color(0xFF62D2F4),
    onSecondary: Color(0xFFFFFFFF),
    surface: Color(0xFF202939),
    onSurface: Color(0xFFFFFFFF),
    onSurfaceVariant: Color(0xFF9AA4B2),
    surfaceContainerLow: Color(0xFF0A0E14),
    surfaceContainerHigh: Color(0xFF000000),
    outline: Color(0xFF364152),
    outlineVariant: Color(0xFF202939),
    error: Color(0xFFFF6C8B),
    onError: Color(0xFF121926),
    success: Color(0xFF89D744),
    onSuccess: Color(0xFF0A0E14),
    warning: Color(0xFFFCD34D),
    onWarning: Color(0xFFFFFFFF),
    inverseSurface: Color(0xFFFFFFFF),
    onInverseSurface: Color(0xFF121926),
    background: Color(0xFF0A0E14),
    backgroundBright: Color(0xFF202939),
    backgroundDim: Color(0xFF000000),
    border: Color(0xFF364152),
    card0: Color(0xFF121926),
    card10: Color(0xFF202939),
    card20: Color(0xFF364152),
    card30: Color(0xFF4B5565),
    card40: Color(0xFF697586),
    contentBlack: Color(0xFFFFFFFF),
    contentGray: Color(0xFF9AA4B2),
    contentGrayBright: Color(0xFF697586),
    contentWhite: Color(0xFF121926),
    divider: Color(0xFF202939),
    errorContainer: Color(0xFFA50C42),
    errorVariant: Color(0xFFE91553),
    errorHover: Color(0xFFFFA0B3),
    logotype: Color(0xFFFFFFFF),
    miscellaneousBlue: Color(0xFFFFFFFF),
    miscellaneousBlueContainer: Color(0xFFFFFFFF),
    miscellaneousBlueHover: Color(0xFFFFFFFF),
    miscellaneousBlueVariant: Color(0xFFFFFFFF),
    miscellaneousEmerald: Color(0xFF10B981),
    miscellaneousEmeraldContainer: Color(0xFFD1FAE5),
    miscellaneousEmeraldHover: Color(0xFF10B981),
    miscellaneousEmeraldVariant: Color(0xFF6EE7B7),
    miscellaneousIndigo: Color(0xFF6366F1),
    miscellaneousIndigoContainer: Color(0xFFC7D2FE),
    miscellaneousIndigoHover: Color(0xFF4F46E5),
    miscellaneousIndigoVariant: Color(0xFF818CF8),
    miscellaneousOnBlueContainer: Color(0xFFFFFFFF),
    miscellaneousOnEmeraldContainer: Color(0xFF065F46),
    miscellaneousOnIndigoContainer: Color(0xFF312E81),
    miscellaneousOnOrangeContainer: Color(0xFF9A3412),
    miscellaneousOnPinkContainer: Color(0xFF9D174D),
    miscellaneousOnVioletContainer: Color(0xFF4C1D95),
    miscellaneousOrange: Color(0xFFF97316),
    miscellaneousOrangeContainer: Color(0xFFFFEDD5),
    miscellaneousOrangeHover: Color(0xFFEA580C),
    miscellaneousOrangeVariant: Color(0xFFFDBA74),
    miscellaneousPink: Color(0xFFEC4899),
    miscellaneousPinkContainer: Color(0xFFFBCFE8),
    miscellaneousPinkHover: Color(0xFFDB2777),
    miscellaneousPinkVariant: Color(0xFFF9A8D4),
    miscellaneousViolet: Color(0xFF7C3AED),
    miscellaneousVioletContainer: Color(0xFFEDE9FE),
    miscellaneousVioletHover: Color(0xFF6D28D9),
    miscellaneousVioletVariant: Color(0xFFC4B5FD),
    onErrorContainer: Color(0xFFFFE3E7),
    onSecondaryContainer: Color(0xFFBDEAFA),
    onSuccessContainer: Color(0xFFE5F8CF),
    onWarningContainer: Color(0xFFFEF3C7),
    primaryHover: Color(0xFF4BC1FF),
    primaryVariant: Color(0xFF0B82FF),
    secondaryContainer: Color(0xFF0D617F),
    secondaryHover: Color(0xFF41CAEF),
    secondaryVariant: Color(0xFF18B3DF),
    successContainer: Color(0xFF345B19),
    successHover: Color(0xFFB1E87D),
    successVariant: Color(0xFF6BBC26),
    warningContainer: Color(0xFF92400E),
    warningHover: Color(0xFFFDE68A),
    warningVariant: Color(0xFFFBBF24),
  );

  /// Neutral / white-label light primary ramp. Dark: use [dark] or add a
  /// second dark palette here when design provides it.
  static const NorthstarColorTokens whiteLabeledLight = NorthstarColorTokens(
    primary: Color(0xFF364152),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFF3F6F9),
    onPrimaryContainer: Color(0xFF121926),
    secondary: Color(0xFF62D2F4),
    onSecondary: Color(0xFF202939),
    surface: Color(0xFFF8FAFC),
    onSurface: Color(0xFF202939),
    onSurfaceVariant: Color(0xFF697586),
    surfaceContainerLow: Color(0xFFF3F6F9),
    surfaceContainerHigh: Color(0xFFE3E8EF),
    outline: Color(0xFFCDD5DF),
    outlineVariant: Color(0xFFE3E8EF),
    error: Color(0xFFE91553),
    onError: Color(0xFFFFFFFF),
    success: Color(0xFF51961A),
    onSuccess: Color(0xFFFFFFFF),
    warning: Color(0xFFFBBF24),
    onWarning: Color(0xFF202939),
    inverseSurface: Color(0xFF00263F),
    onInverseSurface: Color(0xFFFFFFFF),
    background: Color(0xFFF3F6F9),
    backgroundBright: Color(0xFFF8FAFC),
    backgroundDim: Color(0xFFE3E8EF),
    border: Color(0xFFCDD5DF),
    card0: Color(0xFFFFFFFF),
    card10: Color(0xFFF8FAFC),
    card20: Color(0xFFF3F6F9),
    card30: Color(0xFFE3E8EF),
    card40: Color(0xFFCDD5DF),
    contentBlack: Color(0xFF202939),
    contentGray: Color(0xFF697586),
    contentGrayBright: Color(0xFF9AA4B2),
    contentWhite: Color(0xFFFFFFFF),
    divider: Color(0xFFE3E8EF),
    errorContainer: Color(0xFFFFE3E7),
    errorVariant: Color(0xFFFF6C8B),
    errorHover: Color(0xFFC50B46),
    logotype: Color(0xFF00263F),
    miscellaneousBlue: Color(0xFF046AF2),
    miscellaneousBlueContainer: Color(0xFFEDF9FF),
    miscellaneousBlueHover: Color(0xFF0B54C2),
    miscellaneousBlueVariant: Color(0xFF22A1FF),
    miscellaneousEmerald: Color(0xFF10B981),
    miscellaneousEmeraldContainer: Color(0xFFD1FAE5),
    miscellaneousEmeraldHover: Color(0xFF10B981),
    miscellaneousEmeraldVariant: Color(0xFF6EE7B7),
    miscellaneousIndigo: Color(0xFF6366F1),
    miscellaneousIndigoContainer: Color(0xFFC7D2FE),
    miscellaneousIndigoHover: Color(0xFF4F46E5),
    miscellaneousIndigoVariant: Color(0xFF818CF8),
    miscellaneousOnBlueContainer: Color(0xFF104A98),
    miscellaneousOnEmeraldContainer: Color(0xFF065F46),
    miscellaneousOnIndigoContainer: Color(0xFF312E81),
    miscellaneousOnOrangeContainer: Color(0xFF9A3412),
    miscellaneousOnPinkContainer: Color(0xFF9D174D),
    miscellaneousOnVioletContainer: Color(0xFF4C1D95),
    miscellaneousOrange: Color(0xFFF97316),
    miscellaneousOrangeContainer: Color(0xFFFFEDD5),
    miscellaneousOrangeHover: Color(0xFFEA580C),
    miscellaneousOrangeVariant: Color(0xFFFDBA74),
    miscellaneousPink: Color(0xFFEC4899),
    miscellaneousPinkContainer: Color(0xFFFBCFE8),
    miscellaneousPinkHover: Color(0xFFDB2777),
    miscellaneousPinkVariant: Color(0xFFF9A8D4),
    miscellaneousViolet: Color(0xFF7C3AED),
    miscellaneousVioletContainer: Color(0xFFEDE9FE),
    miscellaneousVioletHover: Color(0xFF6D28D9),
    miscellaneousVioletVariant: Color(0xFFC4B5FD),
    onErrorContainer: Color(0xFFA50C42),
    onSecondaryContainer: Color(0xFF0B91BE),
    onSuccessContainer: Color(0xFF345B19),
    onWarningContainer: Color(0xFF92400E),
    primaryHover: Color(0xFF202939),
    primaryVariant: Color(0xFF697586),
    secondaryContainer: Color(0xFFE1F5FD),
    secondaryHover: Color(0xFF41CAEF),
    secondaryVariant: Color(0xFFBDEAFA),
    successContainer: Color(0xFFE5F8CF),
    successHover: Color(0xFF3F7318),
    successVariant: Color(0xFF89D744),
    warningContainer: Color(0xFFFEF3C7),
    warningHover: Color(0xFFF59E0B),
    warningVariant: Color(0xFFFDE68A),
  );
}
